# Generated by Django 3.1 on 2020-10-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checks', '0002_auto_20201002_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='descripcion',
            field=models.TextField(max_length=255),
        ),
    ]
